### ISSUE TITLE
teknoasian.com

### ISSUE THREAD

**Issue by KaKi87** [FastForwardTeam/FastForward#1129]
### Link

https://teknoasian.com/?id=Ti9GbjJERVpiTmtNY1RGRWQyVURvQ3A4RHc5NW1pcit2RnBDSFRFRmtPVlVLc2hnZWgyRlFVSUgxSVJYWjJBakZQQmJsYzFwYjdBc1JVSGxyMndLaGc9PQ==

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Phone (Android)

### (Optional) Anything else?

I would also like to know if the Manifest V2 version supports more URLs and if yes then where to download it.

Thanks

**Comment by KaKi87** [comment]
*Activity*

**Comment by KaKi87** [comment]
*Activity*

**Comment by sharoon7171** [comment]
@KaKi87 You can bypass Teknoasian with this extension.

https://chromewebstore.google.com/detail/hdoecnlghjglmnjpnhaaeofcgocdgkhd

**Comment by KaKi87** [comment]
Thanks, though next time disclose you're the author, also it would be nice to have the GitHub link in the extension description, and finally, are you planning on supporting Firefox ?

**Comment by sharoon7171** [comment]
https://github.com/sharoon7171/skip-wait-bypass-timers-countdowns-extension

**Comment by KaKi87** [comment]
*in the extension description*.

**Comment by undeadjess** [comment]
@sharoon7171,

> [@KaKi87](https://github.com/KaKi87) You can bypass Teknoasian with this extension.
> 
> https://chromewebstore.google.com/detail/hdoecnlghjglmnjpnhaaeofcgocdgkhd

you messaged me last week about listing your extension on our readme, and i told you that i would list it as recommended by us if you proved that you could maintain it. i was concerned because it is relatively new and almost entirely AI generated, down to even your commit messages. 

obviously you didnt feel this was reasonable, as you have now taken to spamming your extension in issues in this repo, while never mentioning that you are the developer.

because of this, and the way you spoke about "wanting more users", i dont believe that your intentions are actually to maintain your extension as foss, but rather to either gain users then sell it, or introduce slightly-less-that-ethical monetary streams. in this case, we could not recommend it. even if that is not the case, your spam is unacceptable.
