### ISSUE TITLE
Fastforward got removed from the chrome web store

### ISSUE THREAD

**Issue by zqpvr** [FastForwardTeam/FastForward#1306]
### Body

It got removed

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by muchqs** [comment]
yep.
RIP.

**Comment by KaladinDMP** [comment]
I for one am wondering what it supposedly violated, it must be pretty new because the official site still links to the chrome extension store. I get there are other ways to install it but wondering why it was removed. Chrome can be pretty dumb about their reasons my friends app was removed from the extension store because it wasnt working for people in australia a bit more to it but that was the crux of the issue, so im sure its nothing serious but i am curious and to be safe would rather know before i reenable it.

**Comment by 0r3z3r0c** [comment]
On Edge (extension installed from Chrome Store) the extension got flagged as a malware

**Comment by pantantrollo** [comment]
> On Edge (extension installed from Chrome Store) the extension got flagged as a malware

The MS Edge store is still active

**Comment by ilike2burnthing** [comment]
Back up.

**Comment by zqpvr** [comment]
I wonder what happened

**Comment by NotAProton** [comment]
> I wonder what happened

It was removed because we missed to remove a permission while porting to MV3. Google flagged it as malware for requesting unused permissions.
