### ISSUE TITLE
hCaptcha cookies aren't working

### ISSUE THREAD

**Issue by IrishBumfuzzle** [FastForwardTeam/FastForward#145]
### Body

I use hCaptcha accessibility cookies to bypass captchas, found [here](https://dashboard.hcaptcha.com/welcome_accessibility). When I click to `set cookie`  it gives out an error and disabling fast forward fixes this.

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloggerpemula** [comment]
yes this is true ,i have same problem in my firefox browser , after disabling fastforward extension i can set the cookie, please fix it asap.

**Comment by NotAProton** [comment]
afaik, fastforward doesn't have anything to do with cookies

**Comment by SweetLoli** [comment]
Thank you! I also had a problem with hCaptcha not getting accessibility cookies, after disabling FastForward it worked fine

**Comment by bloggerpemula** [comment]
> 
> afaik, fastforward doesn't have anything to do with cookies

yes that true , but since this week there is a conflicting script between hcaptcha and fastforward extension , i see universal bypass have same problem too,this mean the problem come from old script code but i don't know which script code that make conflict , but i see error code "401 Unauthorized" if the extension is active . this problem make hard to solve hcaptcha , i hope you can fix this soon .
for everyone that have problems like this , don't tick  Enable website bypasses. when you solve Hcaptcha

**Comment by IrishBumfuzzle** [comment]
@NotAProton is there any fixes or progress regarding this?
