### ISSUE TITLE
tei.ai redirects incorrectly

### ISSUE THREAD

**Issue by imwaitingnow** [FastForwardTeam/FastForward#179]
### Domain

tei.ai

### Link

https://tei.ai/mTWd

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

its suposed to redirect to https://turkdebrid.net/media/********* but just gives a 404 error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ruakij** [comment]
After this redirect, there is another, very similar looking, site "iir.ai" without a bypass, i'll create one shortly.

But because these sites looks so similar i think they might choose a random style every time.
Do you have another domain from the same source that might have a second captcha-site behind it?

**Comment by imwaitingnow** [comment]
will this do https://linksly.co/lWa5sv this also redirects to turkdebrid put properly
