### ISSUE TITLE
tii.ai bypass broken

### ISSUE THREAD

**Issue by gosndka** [FastForwardTeam/FastForward#288]
### Domain

tii.ai

### Link

https://tii.ai/ARsen2x

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

The extension bypasses it to "https://s"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by diieg707** [comment]
Original Code:

```js
domainBypass("tei.ai", () => {
	ensureDomLoaded(() => {
	    var link = atob("aH" + document.querySelector("#link-view [name='token']").value.split("aH")[2]);
	    safelyNavigate(link);
	});
});
```
---
atob("aH" + document.querySelector("#link-view [name='token']").value.split("aH")[1]); = the "1" in the end retrieves the first half of link
https://s
atob("aH" + document.querySelector("#link-view [name='token']").value.split("aH")[2]);  = the "2" in the end retrieves the second half
hrinke.me/hT7FLQC5

in this case i guess we need to concatenate the two strings, so that would be something like this: 

```js
domainBypass("tei.ai", () => {
	ensureDomLoaded(() => {
	    var link = atob("aH" + document.querySelector("#link-view [name='token']").value.split("aH")[1]);
	    var link2 = atob("aH" + document.querySelector("#link-view [name='token']").value.split("aH")[2]);
	    var result = link.concat(link2);
	    safelyNavigate(result);
	});
});
```

the link.concat(link2) command worked on chrome console but i was not able to get it working using that custom bypass window on fastward options.

**Comment by reashetyrr** [comment]
they inserted junk, appending the aH and splitting on it doesnt work, just atob to decode the base64 and pop on the split to http to append http again
