### ISSUE TITLE
za.gl

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#53]
### Domain

za.gl

### Link

https://zee.gl/wj7ojzo

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

```
https://zee.gl/wj7ojzo
https://za.gl/1Wo5q
https://za.uy/NHtP
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
Captcha & can be bypassed with Crowd Bypass.

**Comment by RohanDebroy** [comment]
HI @lem6ns, Can you please try this bypass for `za.gl`

```
ensureDomLoaded(() => {
  domainBypass(/za\.(gl|uy)/, () => {
    //Takes care of the captcha
    ifElement("form#link-view", form => {
      document.querySelector('#x').value = '192'
	    document.querySelector('#y').value = '114'
	    document.querySelector('input[name="givenX"]').value = 'VFl0utOEF6a7BiS8YJdqTg=='
	    document.querySelector('input[name="givenY"]').value = 'rsW06vBB1oIFVpnFz61t5Q=='
      form.submit()
      return
    })

    //Bypasses the second screen where you have to view three 5 sec ads.
    ifElement("form#go-link", form => {
      window.setTimeout(() => {
        let payload = new URLSearchParams(new FormData(form)).toString();
        fetch(`${location.origin}/links/go`, {
          "headers": {
            "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
            "x-requested-with": "XMLHttpRequest"
          },
          "body":payload,
          "method": "POST",
          "mode": "cors",
        })
        .then(res => res.json())
        .then(res => {
            if(res.status === "error"){
              crowdBypass()
              return
            }
            safelyNavigate(res.url)
        })
      }, 3000)
    }, () => crowdBypass())
  })
})
```

The only issue with this method is you have to wait for 3seconds before you are navigated to the actual URL.

**Comment by Vojtak42** [comment]
Does not work in kiwi browser.

**Comment by NotAProton** [comment]
you have to wait 2-3 seconds because of server-side checks

**Comment by Vojtak42** [comment]
it was caused by the ublock origin when I disabled ublock, it worked right.

**Comment by RohanDebroy** [comment]
> it was caused by the ublock origin when I disabled ublock, it worked right.

Not only ublock origin but most of the ad blockers because they share the same ad filters. But you see the filter specifically blocks the `za.gl` domain and `za.uy` domain seems to be unaffected by the ad filters.

What I would suggest is to replace the `za.gl` from your shortened URL with `za.uy` instead of disabling the adblocker.

Example-
`https://zee.gl/wj7ojzo` --> `https://za.uy/wj7ojzo` //it will redirect to the same URL as  the zee.gl one
`https://za.gl/1Wo5q` --> `https://za.uy/1Wo5q` //it will redirect to the same URL as  the za.gl one
`https://za.uy/NHtP`

And if you feel like this is too much of a work, then just disable unlock for za.gl domain

**Comment by Vojtak42** [comment]
Thank you, it works. I solved it by installing adguard adblocker and disabling ublock for this domain and it works too.
