### ISSUE TITLE
9desires.cc bypass not working

### ISSUE THREAD

**Issue by agent-talha** [FastForwardTeam/FastForward#763]
### Domain

9desires.cc

### Link

https://9desires.cc/?id=dUhNeFFrNHIyd05PM1BKTHZCQ0lOaDRFa1VaOFBxMkhtc3lLSVg4TkdCc0Jsd0hKU251MHMvcHFYenNaWFRDSHhveFlaenV4L05jb1B2djlWdUNkV1VMaXBjYjVZbVNlWU1Ra253STM1TmozRkVGVWRZWU1hSTVLUDBEL0Z5VmI=

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome, Brave, Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
@N0-0NE-Dev base64, maybe the final link is there?

**Comment by abadawe-dev** [comment]
> @N0-0NE-Dev base64, maybe the final link is there?

Yeah for sure it has something to do with the final link, because normally going to these websites just lead to their homepage, but it decodes to

uHMxQk4r2wNO3PJLvBCINh4EkUZ8Pq2HmsyKIX8NGBsBlwHJSnu0s/pqXzsZXTCHxoxYZzux/NcoPvv9VuCdWULipcb5YmSeYMQknwI35Nj3FEFUdYYMaI5KP0D/FyVb

And I have no idea what kind of encoding this is.

**Comment by abadawe-dev** [comment]
> @N0-0NE-Dev base64, maybe the final link is there?

Also this seems to come from the same "family" as "indiainfo4u.in", they use the same base64 id in the url.

**Comment by ghost** [comment]
While this is a new bypass, other devs have commented possible solutions, so this issue will stay open.
