### ISSUE TITLE
Not bypassing ouo.io

### ISSUE THREAD

**Issue by UMuktesh** [FastForwardTeam/FastForward#850]
### Domain

https://ouo.io

### Link

https://ouo.io/W0WO4w

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Version 0.2182.0

**Comment by ghost** [comment]
You were probably the first to encounter that link, so that's why you had to wait. ouo.io utilizes a crowd bypasses due to the timer, so we cannot bypass it automatically. I was able to instantly get to the mega.nz link (video below).


https://user-images.githubusercontent.com/45770865/210405135-d96bab91-2af6-4653-9d1e-86dd932728c1.mp4
