### ISSUE TITLE
Extension options issue

### ISSUE THREAD

**Issue by Chaprnks** [FastForwardTeam/FastForward#931]
### Body

Starting with the build 0.2224, I noticed the download bypass definitions remains stuck at "DOWNLOADING BYPASS DEFINITIONS...". I'm not sure if this is just cosmetic, or actually an issue with the downloading of the definitions. Thought it was worth while to report this bug, as I couldn't find a duplicate report on the GitHub open issues.

### Version

0.02224

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![YSXpUMj](https://user-images.githubusercontent.com/6340970/229365123-93b0a43e-b39a-4dfd-8225-840a12914920.png)

**Comment by lostdusty** [comment]
Know issue, will be fixed in MV3.

**Comment by NomarCub** [comment]
Is there an issue that tracks MV3 progress? When can it be expected to release? Will there be a change in functionality?

**Comment by NomarCub** [comment]
I found some answers at the [latest release](https://github.com/FastForwardTeam/FastForward/releases/tag/0.2237), you should've at least linked this here.
But I still don't have answers to all my questions. What should someone do who just wants to install the extension *now*? Switch to an older, stable version on MV2 or to a new, nightly version on some MV3 branch? What is the timeline on MV3 development and release?

**Comment by ghost** [comment]
> I found some answers at the [latest release](https://github.com/FastForwardTeam/FastForward/releases/tag/0.2237), you should've at least linked this here. But I still don't have answers to all my questions. What should someone do who just wants to install the extension _now_? Switch to an older, stable version on MV2 or to a new, nightly version on some MV3 branch? What is the timeline on MV3 development and release?

As of right now, the developers recommend staying on the MV2 extension; the MV3 extension has some broken functionality such as:

- Crowd bypass functionality still being fixed
- IP logger bypassing and blocking broken due to discontinued API
- Absence of many bypasses due to the need for manual translation to MV3

You can use the MV3 extension, but doing so means losing core functionality. We're pushing for a summer 2023 release of the MV3 extension, but that depends on how fast MV2 bypasses can be translated to MV3, as all other functionality has been successfully ported.

**Comment by NomarCub** [comment]
Thanks!
You should put all this in the readme too, so people can find it easily.

What version of the MV2 extension is free of this bug, with "DOWNLOADING BYPASS DEFINITIONS..." displaying indefinitely? Is it just cosmetic like the poster suspected @princessmortix? Is there a quick local fix for it perhaps?
